### ISSUE TITLE
Run on Windows 

### ISSUE THREAD

**Issue by sanbroz** [JorenSix/Panako#24]
I am trying to run Panako on windows 10. So far I managed to compile using ant. Using store parameter with input mp3 from file.txt gives following output only

**java -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -Xms256m -Xmx256m -Djava.util.logging.config.file=logging.properties -jar panako-2.0.jar store list.txt**
_Audiofile;Audio duration;Fingerprinting duration;ratio_

stats command 

**java -server -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -Xms256m -Xmx256m -Djava.util.logging.config.file=logging.properties -jar panako-2.0.jar stats**
_Exception in thread "main" java.lang.IllegalArgumentException: Unknown result code 112
        at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:111)
        at org.lmdbjava.Env$Builder.open(Env.java:495)
        at org.lmdbjava.Env$Builder.open(Env.java:512)
        at be.panako.strategy.olaf.storage.OlafStorageKV.<init>(Unknown Source)
        at be.panako.strategy.olaf.storage.OlafStorageKV.getInstance(Unknown Source)
        at be.panako.strategy.olaf.OlafStrategy.printStorageStatistics(Unknown Source)
        at be.panako.cli.Stats.run(Unknown Source)
        at be.panako.cli.Panako.actuallyReallyStartApplication(Unknown Source)
        at be.panako.cli.Panako.actuallyStartApplication(Unknown Source)
        at be.panako.cli.Panako.startApplication(Unknown Source)
        at be.panako.cli.Panako.main(Unknown Source)_

Can anyone help me to get it running in windows environment?

**Comment by JorenSix** [comment]
Hi,

I have been able to reproduce the problem. I run into a similar problem (with the same error code) even with the newer java lmdb version. The LMDB dependency can be skipped by using an in memory database. Then this error does not appear.

But, there is also another problem with running Panako on Windows. The way audio is decoded and resampled is currently problematic on windows. The way ffmpeg is called is not compatible with Windows.

 However, [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) offers a way in which to run Panako on _Windows_. _'WSL enables you to use Linux tools, like Bash or Grep [...], with no need to dual-boot.'_  I have managed to run Panako on WSL without any issues. With this option in mind, pure Windows support is not a priority.
